<?php

return [
    'organization.company_name' => [
        'default' => 'HRIS',
        'type' => 'string',
        'group' => 'organization',
        'label' => 'Company name',
        'description' => 'The organization name shown in company-wide settings.',
        'rules' => ['required', 'string', 'max:120'],
    ],
    'organization.timezone' => [
        'default' => 'Asia/Manila',
        'type' => 'string',
        'group' => 'organization',
        'label' => 'Company timezone',
        'description' => 'The timezone used when interpreting attendance policy.',
        'rules' => ['required', 'timezone'],
    ],
    'attendance.photo_capture_enabled' => [
        'default' => true,
        'type' => 'boolean',
        'group' => 'attendance',
        'label' => 'Allow attendance photos',
        'description' => 'Employees may attach an optional photo when timing in or out.',
        'rules' => ['required', 'boolean'],
    ],
    'attendance.location_capture_enabled' => [
        'default' => true,
        'type' => 'boolean',
        'group' => 'attendance',
        'label' => 'Capture attendance location',
        'description' => 'Ask the browser for the employee location during time in and time out.',
        'rules' => ['required', 'boolean'],
    ],
    'attendance.location_required' => [
        'default' => false,
        'type' => 'boolean',
        'group' => 'attendance',
        'label' => 'Require attendance location',
        'description' => 'Block attendance capture if a location cannot be obtained.',
        'rules' => ['required', 'boolean'],
    ],
    'attendance.notes_enabled' => [
        'default' => true,
        'type' => 'boolean',
        'group' => 'attendance',
        'label' => 'Allow attendance notes',
        'description' => 'Show an optional note during time in and time out.',
        'rules' => ['required', 'boolean'],
    ],
    'attendance.capture_ip_enabled' => [
        'default' => true,
        'type' => 'boolean',
        'group' => 'attendance',
        'label' => 'Record IP address',
        'description' => 'Store the source IP address for each attendance action.',
        'rules' => ['required', 'boolean'],
    ],
    'attendance.manual_entries_enabled' => [
        'default' => true,
        'type' => 'boolean',
        'group' => 'attendance',
        'label' => 'Allow manual attendance records',
        'description' => 'Allow administrators to create, correct, or delete attendance records.',
        'rules' => ['required', 'boolean'],
    ],
    'attendance.photo_max_size_mb' => [
        'default' => 5,
        'type' => 'integer',
        'group' => 'attendance',
        'label' => 'Attendance photo size limit',
        'description' => 'Maximum size of each attendance photo in megabytes.',
        'rules' => ['required', 'integer', 'min:1', 'max:10'],
    ],
    'leave.attachments_enabled' => [
        'default' => true,
        'type' => 'boolean',
        'group' => 'leave',
        'label' => 'Allow leave attachments',
        'description' => 'Allow supporting documents on leave requests.',
        'rules' => ['required', 'boolean'],
    ],
    'messaging.realtime_enabled' => [
        'default' => true,
        'type' => 'boolean',
        'group' => 'messaging',
        'label' => 'Real-time messaging',
        'description' => 'Allow clients to connect to Reverb for live conversation updates.',
        'rules' => ['required', 'boolean'],
    ],
    'notifications.success_alerts_enabled' => [
        'default' => true,
        'type' => 'boolean',
        'group' => 'experience',
        'label' => 'Success alerts',
        'description' => 'Show global success notifications after create, update, and delete actions.',
        'rules' => ['required', 'boolean'],
    ],
];
