<?php

return [
    'organization.company_name' => [
        'default' => 'HRIS',
        'type' => 'string',
        'group' => 'organization',
        'label' => 'Company name',
        'description' => 'The organization name shown in company-wide settings.',
        'rules' => ['required', 'string', 'max:120'],
    ],
    'organization.timezone' => [
        'default' => 'Asia/Manila',
        'type' => 'string',
        'group' => 'organization',
        'label' => 'Company timezone',
        'description' => 'The timezone used when interpreting attendance policy.',
        'rules' => ['required', 'timezone'],
    ],
    'attendance.photo_capture_enabled' => [
        'default' => true,
        'type' => 'boolean',
        'group' => 'attendance',
        'label' => 'Allow attendance photos',
        'description' => 'Employees may attach an optional photo when timing in or out.',
        'rules' => ['required', 'boolean'],
    ],
    'attendance.location_capture_enabled' => [
        'default' => true,
        'type' => 'boolean',
        'group' => 'attendance',
        'label' => 'Capture attendance location',
        'description' => 'Ask the browser for the employee location during time in and time out.',
        'rules' => ['required', 'boolean'],
    ],
    'attendance.location_required' => [
        'default' => false,
        'type' => 'boolean',
        'group' => 'attendance',
        'label' => 'Require attendance location',
        'description' => 'Block attendance capture if a location cannot be obtained.',
        'rules' => ['required', 'boolean'],
    ],
    'attendance.notes_enabled' => [
        'default' => true,
        'type' => 'boolean',
        'group' => 'attendance',
        'label' => 'Allow attendance notes',
        'description' => 'Show an optional note during time in and time out.',
        'rules' => ['required', 'boolean'],
    ],
    'attendance.capture_ip_enabled' => [
        'default' => true,
        'type' => 'boolean',
        'group' => 'attendance',
        'label' => 'Record IP address',
        'description' => 'Store the source IP address for each attendance action.',
        'rules' => ['required', 'boolean'],
    ],
    'attendance.manual_entries_enabled' => [
        'default' => true,
        'type' => 'boolean',
        'group' => 'attendance',
        'label' => 'Allow manual attendance records',
        'description' => 'Allow administrators to create, correct, or delete attendance records.',
        'rules' => ['required', 'boolean'],
    ],
    'attendance.photo_max_size_mb' => [
        'default' => 5,
        'type' => 'integer',
        'group' => 'attendance',
        'label' => 'Attendance photo size limit',
        'description' => 'Maximum size of each attendance photo in megabytes.',
        'rules' => ['required', 'integer', 'min:1', 'max:10'],
    ],
    'leave.attachments_enabled' => [
        'default' => true,
        'type' => 'boolean',
        'group' => 'leave',
        'label' => 'Allow leave attachments',
        'description' => 'Allow supporting documents on leave requests.',
        'rules' => ['required', 'boolean'],
    ],
    'messaging.realtime_enabled' => [
        'default' => true,
        'type' => 'boolean',
        'group' => 'messaging',
        'label' => 'Real-time messaging',
        'description' => 'Allow clients to connect to Reverb for live conversation updates.',
        'rules' => ['required', 'boolean'],
    ],
    'messaging.attachments_enabled' => [
        'default' => true,
        'type' => 'boolean',
        'group' => 'messaging',
        'label' => 'Message attachments',
        'description' => 'Allow conversation participants to exchange photos and files.',
        'rules' => ['required', 'boolean'],
    ],
    'messaging.max_attachment_size_mb' => [
        'default' => 25,
        'type' => 'integer',
        'group' => 'messaging',
        'label' => 'Message attachment size limit',
        'description' => 'Maximum size of each file sent through Messages.',
        'rules' => ['required', 'integer', 'min:1', 'max:50'],
    ],
    'notifications.success_alerts_enabled' => [
        'default' => true,
        'type' => 'boolean',
        'group' => 'experience',
        'label' => 'Success alerts',
        'description' => 'Show global success notifications after create, update, and delete actions.',
        'rules' => ['required', 'boolean'],
    ],
    'employee_documents.enabled' => [
        'default' => true,
        'type' => 'boolean',
        'group' => 'employee_documents',
        'label' => 'Employee 201 files',
        'description' => 'Allow authorized users and employees to access secure personnel documents.',
        'rules' => ['required', 'boolean'],
    ],
    'employee_documents.max_size_mb' => [
        'default' => 10,
        'type' => 'integer',
        'group' => 'employee_documents',
        'label' => '201 file size limit',
        'description' => 'Maximum size of each personnel document in megabytes.',
        'rules' => ['required', 'integer', 'min:1', 'max:25'],
    ],
    'payroll.enabled' => [
        'default' => true,
        'type' => 'boolean',
        'group' => 'payroll',
        'label' => 'Payroll module',
        'description' => 'Enable payroll periods, calculation, approval, and employee payslips.',
        'rules' => ['required', 'boolean'],
    ],
    'payroll.currency' => [
        'default' => 'PHP',
        'type' => 'string',
        'group' => 'payroll',
        'label' => 'Payroll currency',
        'description' => 'Currency used for payroll amounts.',
        'rules' => ['required', 'in:PHP'],
    ],
    'payroll.default_frequency' => [
        'default' => 'semi_monthly',
        'type' => 'string',
        'group' => 'payroll',
        'label' => 'Default pay frequency',
        'description' => 'Default frequency for newly created payroll periods.',
        'rules' => ['required', 'in:monthly,semi_monthly'],
    ],
    'payroll.work_days_per_month' => [
        'default' => 22,
        'type' => 'number',
        'group' => 'payroll',
        'label' => 'Work days per month',
        'description' => 'Divisor used to calculate an employee hourly rate.',
        'rules' => ['required', 'numeric', 'min:1', 'max:31'],
    ],
    'payroll.hours_per_day' => [
        'default' => 8,
        'type' => 'number',
        'group' => 'payroll',
        'label' => 'Hours per work day',
        'description' => 'Hours used to derive an employee hourly rate.',
        'rules' => ['required', 'numeric', 'min:1', 'max:24'],
    ],
    'payroll.overtime_multiplier' => [
        'default' => 1.25,
        'type' => 'number',
        'group' => 'payroll',
        'label' => 'Regular overtime multiplier',
        'description' => 'Multiplier applied to approved overtime hours. Configure special-day premiums separately before production use.',
        'rules' => ['required', 'numeric', 'min:1', 'max:5'],
    ],
    'payroll.attendance_calculation_enabled' => [
        'default' => true,
        'type' => 'boolean',
        'group' => 'payroll_attendance',
        'label' => 'Use attendance in payroll',
        'description' => 'Generate payroll work summaries from attendance and approved leave records.',
        'rules' => ['required', 'boolean'],
    ],
    'payroll.work_weekdays' => [
        'default' => [1, 2, 3, 4, 5],
        'type' => 'array',
        'group' => 'payroll_attendance',
        'label' => 'Scheduled weekdays',
        'description' => 'ISO weekdays considered scheduled workdays, where Monday is 1 and Sunday is 7.',
        'rules' => ['required', 'array', 'min:1'],
    ],
    'payroll.scheduled_start_time' => [
        'default' => '09:00',
        'type' => 'string',
        'group' => 'payroll_attendance',
        'label' => 'Scheduled start time',
        'description' => 'Company default used to calculate late minutes.',
        'rules' => ['required', 'date_format:H:i'],
    ],
    'payroll.scheduled_end_time' => [
        'default' => '18:00',
        'type' => 'string',
        'group' => 'payroll_attendance',
        'label' => 'Scheduled end time',
        'description' => 'Company default used to calculate undertime minutes.',
        'rules' => ['required', 'date_format:H:i'],
    ],
    'payroll.grace_minutes' => [
        'default' => 0,
        'type' => 'integer',
        'group' => 'payroll_attendance',
        'label' => 'Late grace period',
        'description' => 'Minutes after the scheduled start before late time begins.',
        'rules' => ['required', 'integer', 'min:0', 'max:180'],
    ],
    'payroll.deduct_absences' => [
        'default' => true,
        'type' => 'boolean',
        'group' => 'payroll_attendance',
        'label' => 'Deduct absences',
        'description' => 'Deduct uncovered scheduled workdays from payroll.',
        'rules' => ['required', 'boolean'],
    ],
    'payroll.deduct_late_undertime' => [
        'default' => true,
        'type' => 'boolean',
        'group' => 'payroll_attendance',
        'label' => 'Deduct late and undertime',
        'description' => 'Deduct late and undertime using the derived per-minute rate.',
        'rules' => ['required', 'boolean'],
    ],
    'payroll.deduct_unpaid_leave' => [
        'default' => true,
        'type' => 'boolean',
        'group' => 'payroll_attendance',
        'label' => 'Deduct unpaid leave',
        'description' => 'Deduct approved leave types marked as unpaid.',
        'rules' => ['required', 'boolean'],
    ],
    'payroll.sss_employee_rate' => [
        'default' => 0.05,
        'type' => 'number',
        'group' => 'payroll_sss',
        'label' => 'SSS employee rate',
        'description' => 'Effective January 2025.',
        'rules' => ['required', 'numeric', 'min:0', 'max:1'],
    ],
    'payroll.sss_employer_rate' => [
        'default' => 0.10,
        'type' => 'number',
        'group' => 'payroll_sss',
        'label' => 'SSS employer rate',
        'description' => 'Effective January 2025.',
        'rules' => ['required', 'numeric', 'min:0', 'max:1'],
    ],
    'payroll.sss_min_msc' => [
        'default' => 5000,
        'type' => 'number',
        'group' => 'payroll_sss',
        'label' => 'SSS minimum MSC',
        'description' => 'Minimum Monthly Salary Credit effective January 2025.',
        'rules' => ['required', 'numeric', 'min:0'],
    ],
    'payroll.sss_max_msc' => [
        'default' => 35000,
        'type' => 'number',
        'group' => 'payroll_sss',
        'label' => 'SSS maximum MSC',
        'description' => 'Maximum Monthly Salary Credit effective January 2025.',
        'rules' => ['required', 'numeric', 'min:0'],
    ],
    'payroll.sss_ec_low' => [
        'default' => 10,
        'type' => 'number',
        'group' => 'payroll_sss',
        'label' => 'SSS EC lower amount',
        'description' => 'Employer-only EC contribution at or below the threshold.',
        'rules' => ['required', 'numeric', 'min:0'],
    ],
    'payroll.sss_ec_high' => [
        'default' => 30,
        'type' => 'number',
        'group' => 'payroll_sss',
        'label' => 'SSS EC upper amount',
        'description' => 'Employer-only EC contribution above the threshold.',
        'rules' => ['required', 'numeric', 'min:0'],
    ],
    'payroll.sss_ec_threshold' => [
        'default' => 14500,
        'type' => 'number',
        'group' => 'payroll_sss',
        'label' => 'SSS EC MSC threshold',
        'description' => 'MSC threshold separating the lower and upper EC amount.',
        'rules' => ['required', 'numeric', 'min:0'],
    ],
    'payroll.philhealth_rate' => [
        'default' => 0.05,
        'type' => 'number',
        'group' => 'payroll_philhealth',
        'label' => 'PhilHealth premium rate',
        'description' => 'Premium rate retained for calendar year 2025.',
        'rules' => ['required', 'numeric', 'min:0', 'max:1'],
    ],
    'payroll.philhealth_salary_floor' => [
        'default' => 10000,
        'type' => 'number',
        'group' => 'payroll_philhealth',
        'label' => 'PhilHealth income floor',
        'description' => 'Monthly basic salary floor for premium calculation.',
        'rules' => ['required', 'numeric', 'min:0'],
    ],
    'payroll.philhealth_salary_ceiling' => [
        'default' => 100000,
        'type' => 'number',
        'group' => 'payroll_philhealth',
        'label' => 'PhilHealth income ceiling',
        'description' => 'Monthly basic salary ceiling for premium calculation.',
        'rules' => ['required', 'numeric', 'min:0'],
    ],
    'payroll.pagibig_employee_rate_low' => [
        'default' => 0.01,
        'type' => 'number',
        'group' => 'payroll_pagibig',
        'label' => 'Pag-IBIG lower employee rate',
        'description' => 'Employee rate for monthly compensation of ₱1,500 and below.',
        'rules' => ['required', 'numeric', 'min:0', 'max:1'],
    ],
    'payroll.pagibig_employee_rate' => [
        'default' => 0.02,
        'type' => 'number',
        'group' => 'payroll_pagibig',
        'label' => 'Pag-IBIG employee rate',
        'description' => 'Employee rate for monthly compensation over ₱1,500.',
        'rules' => ['required', 'numeric', 'min:0', 'max:1'],
    ],
    'payroll.pagibig_employer_rate' => [
        'default' => 0.02,
        'type' => 'number',
        'group' => 'payroll_pagibig',
        'label' => 'Pag-IBIG employer rate',
        'description' => 'Required employer counterpart rate.',
        'rules' => ['required', 'numeric', 'min:0', 'max:1'],
    ],
    'payroll.pagibig_rate_threshold' => [
        'default' => 1500,
        'type' => 'number',
        'group' => 'payroll_pagibig',
        'label' => 'Pag-IBIG rate threshold',
        'description' => 'Monthly compensation threshold for the lower employee rate.',
        'rules' => ['required', 'numeric', 'min:0'],
    ],
    'payroll.pagibig_max_salary' => [
        'default' => 10000,
        'type' => 'number',
        'group' => 'payroll_pagibig',
        'label' => 'Pag-IBIG maximum fund salary',
        'description' => 'Maximum fund salary used for mandatory savings.',
        'rules' => ['required', 'numeric', 'min:0'],
    ],
];
