<?php

return [
    /*
     * These endpoints deliberately authorize against the authenticated user,
     * a resource owner, or a conversation participant inside the controller.
     * Keep every exception documented here so authorization:audit --strict can
     * fail when a newly added authenticated endpoint has no policy boundary.
     */
    'controller_authorized_actions' => [
        'App\\Http\\Controllers\\Auth\\AuthController@logout' => 'Current-session action.',
        'App\\Http\\Controllers\\Auth\\AuthController@authUser' => 'Current-user profile.',
        'App\\Http\\Controllers\\Auth\\AuthController@getSettings' => 'Current-user settings.',
        'App\\Http\\Controllers\\Auth\\AuthController@updateSettings' => 'Current-user settings.',
        'App\\Http\\Controllers\\Auth\\AuthController@updatePassword' => 'Current-user credential.',
        'App\\Http\\Controllers\\Auth\\AuthController@mfaStatus' => 'Current-user MFA status.',
        'App\\Http\\Controllers\\Auth\\AuthController@startMfaSetup' => 'Current-user MFA enrollment.',
        'App\\Http\\Controllers\\Auth\\AuthController@confirmMfa' => 'Current-user MFA enrollment.',
        'App\\Http\\Controllers\\Auth\\AuthController@disableMfa' => 'Current-user MFA enrollment.',
        'App\\Http\\Controllers\\Auth\\AuthController@sessions' => 'Current-user sessions.',
        'App\\Http\\Controllers\\Auth\\AuthController@revokeOtherSessions' => 'Current-user sessions.',
        'App\\Http\\Controllers\\Auth\\AuthController@revokeSession' => 'Current-user token ownership.',
        'Illuminate\\Broadcasting\\BroadcastController@authenticate' => 'Channel authorization callback.',
        'App\\Http\\Controllers\\Profile\\ProfileController@show' => 'Current-user profile.',
        'App\\Http\\Controllers\\Profile\\ProfileController@update' => 'Current-user profile.',
        'App\\Http\\Controllers\\Profile\\ProfileController@uploadPhoto' => 'Current-user profile.',
        'App\\Http\\Controllers\\Profile\\ProfileController@deletePhoto' => 'Current-user profile.',
        'App\\Http\\Controllers\\Profile\\ProfileController@photo' => 'Profile-photo ownership check.',
        'App\\Http\\Controllers\\Dashboard\\DashboardController@overview' => 'Role-filtered dashboard.',
        'App\\Http\\Controllers\\Dashboard\\DashboardController@layout' => 'Current-user dashboard layout.',
        'App\\Http\\Controllers\\Dashboard\\DashboardController@updateLayout' => 'Current-user dashboard layout.',
        'App\\Http\\Controllers\\Navigation\\NavigationBadgeController' => 'Current-user navigation badges.',
        'App\\Http\\Controllers\\Conversation\\ConversationController@index' => 'Current-user conversations.',
        'App\\Http\\Controllers\\Conversation\\ConversationController@recipients' => 'Current-user messaging recipients.',
        'App\\Http\\Controllers\\Conversation\\ConversationController@store' => 'Tenant-recipient validation.',
        'App\\Http\\Controllers\\Conversation\\ConversationController@show' => 'Conversation-participant check.',
        'App\\Http\\Controllers\\Conversation\\ConversationController@markRead' => 'Conversation-participant check.',
        'App\\Http\\Controllers\\Message\\MessageController@index' => 'Conversation-participant check.',
        'App\\Http\\Controllers\\Message\\MessageController@store' => 'Conversation-participant check.',
        'App\\Http\\Controllers\\Message\\MessageController@attachment' => 'Conversation-participant and attachment ownership check.',
        'App\\Http\\Controllers\\Employee\\EmployeeDocumentController@categories' => 'Static document categories.',
        'App\\Http\\Controllers\\Employee\\EmployeeDocumentController@index' => 'Employee ownership or HR-document permission.',
        'App\\Http\\Controllers\\Employee\\EmployeeDocumentController@download' => 'Employee ownership or HR-document permission.',
        'App\\Http\\Controllers\\Attendance\\AttendanceController@timeIn' => 'Current employee only.',
        'App\\Http\\Controllers\\Attendance\\AttendanceController@timeOut' => 'Current employee only.',
        'App\\Http\\Controllers\\Attendance\\AttendanceController@today' => 'Current employee only.',
        'App\\Http\\Controllers\\Attendance\\AttendanceController@history' => 'Current employee only.',
        'App\\Http\\Controllers\\Attendance\\AttendanceController@photo' => 'Attendance owner or attendance-view permission.',
        'App\\Http\\Controllers\\Attendance\\AttendanceCorrectionController@index' => 'Employee ownership or correction-review permission.',
        'App\\Http\\Controllers\\Attendance\\AttendanceCorrectionController@store' => 'Current employee only.',
        'App\\Http\\Controllers\\LeaveRequest\\LeaveRequestController@cancel' => 'Leave-request ownership check.',
        'App\\Http\\Controllers\\LeaveType\\LeaveTypeController@index' => 'Leave request form catalogue.',
        'App\\Http\\Controllers\\LeaveType\\LeaveTypeController@show' => 'Leave request form catalogue.',
        'App\\Http\\Controllers\\AppSetting\\AppSettingController@index' => 'Permission-filtered settings definitions.',
        'App\\Http\\Controllers\\Payroll\\PayrollController@index' => 'Employee payslips or company payroll permission.',
        'App\\Http\\Controllers\\Payroll\\PayrollController@show' => 'Employee payslip ownership or company payroll permission.',
        'App\\Http\\Controllers\\Payroll\\PayslipArchiveController@download' => 'Employee payslip ownership or company payroll permission.',
        'App\\Http\\Controllers\\Approval\\ApprovalInboxController@index' => 'Current approver only.',
        'App\\Http\\Controllers\\Notification\\AppNotificationController@index' => 'Current-user notifications.',
        'App\\Http\\Controllers\\Notification\\AppNotificationController@read' => 'Current-user notification ownership.',
    ],
];
